[general]
interval = 2.0
meters = true

[rig]
host = "127.0.0.1"
port = 4532

[gps_fallback]
host = "192.168.50.162"
port = 11123

[[sink]]
type = "tui"

[[sink]]
type = "wsjtx"
host = "127.0.0.1"
port = 2237
